language: scala

env:
  - TRAVIS_JDK=8
  - TRAVIS_JDK=11

matrix:
  fast_finish: true
  allow_failures:
    - env: TRAVIS_JDK=11

# Install Jabba and use it with ~ to install the latest (minor) version of the given JDK release
before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version

script:
    # Test with the defaults
  - sbt new file://$PWD --name=hello && pushd hello && sbt test && popd || travis_terminate 1
    # Test with custom name/organization to ensure templating is done correctly
  - sbt new file://$PWD --name=smello --organization=org.eggsample && pushd smello && sbt test && popd || travis_terminate 1

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
    - "$HOME/.jabba/jdk"

before_cache: find "$HOME/.ivy2/cache" -name "ivydata-*.properties" -delete
